name: Compile Check

on:
  push:
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  compile:
    name: Compile Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK-8
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Compile
        run: mvn -B clean compile -T 1C

      - name: Notify on Success
        if: success()
        run: echo "✅ Code compiles successfully"

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Compilation failed"
