name: Compile Check

on:
  push:
    tags-ignore:
      - '*v'
  pull_request:

jobs:
  compile:
    name: Compile Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile
        run: mvn -B clean compile

      - name: Notify on Success
        if: success()
        run: echo "✅ Code compiles successfully"

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Compilation failed"
